### ISSUE TITLE
API endpoint to fetch existing products

### ISSUE THREAD

**Issue by salickc** [wix/wix-restaurants-api#1]
How can I fetch existing products for a restaurant?

**Comment by dleshem** [comment]
The Menu data structure is described here: http://developers.wixrestaurants.com/Data-structures

The same page also links to a "Print Menu" example that retrieves a restaurant's menu using the Wix Restaurants Java SDK, and prints it to the console.

If you rather skip the SDK and work directly with the web-service (generally not recommended), you can use the "get_organization_full" request:
```
curl -X "POST" -H "Content-Type: application/json" -d '{"type":"get_organization_full","organizationId":"8830975305376234"}' "https://api.wixrestaurants.com/v1.1"
```

**Comment by onmyway133** [comment]
@dleshem Don't you get this error https://github.com/wix/wix-restaurants-js-sdk/issues/17 ?
