### ISSUE TITLE
Unable to find app instance ID

### ISSUE THREAD

**Issue by jaweiss8** [wix/wix-restaurants-api#17]
Hi,

I'm following your instructions for authorization, but can't find my website's app instance ID in the console.
Is there another way to find the app instance id?  
Here's what is displaying in the console:
![screen shot 2018-10-17 at 4 47 53 pm](https://user-images.githubusercontent.com/25960243/47122637-7cdc3380-d22c-11e8-8253-329dd6a26593.jpeg)

Thanks

**Comment by danny-stars** [comment]
is there an answer to this??
