### ISSUE TITLE
API endpoint to edit an existing product

### ISSUE THREAD

**Issue by salickc** [wix/wix-restaurants-api#2]
I would like to use an API to change the following:
1. Edit product price
2. Enable/Disable from menu (out-of-stock toggle)

**Comment by dleshem** [comment]
The recommended flow to do this is to retrieve the restaurant's menu, modify it locally, and then set it.

Retrieving a menu is described in http://developers.wixrestaurants.com/Data-structures (see the "Print Menu" example).

To change an item's price, simply change its "price" field.

Changing item availability is done by interacting with its "availability" field. This field is an object that holds the regular weekly availability (as a list of weekly time windows), and a list of availability exceptions. You'll want to add/remove an exception.

To learn more about availability objects, see [wix-restaurants-availability](https://github.com/wix/wix-restaurants-availability) (Java) or [availability4js](https://github.com/wix/availability4js) (JavaScript).

For example, here's the availability object for an item that's currently unavailable (in theory, you can also set start/end dates):
``` json
{
  "exceptions":[
    {"available":false}
  ]
}
```

Finally, you'll want to set the menu to its modified version. This can be done with the "set_menu" request, described in [SetMenuRequest](https://github.com/wix/openrest4j/blob/master/openrest4j-api/src/main/java/com/openrest/v1_1/SetMenuRequest.java).

You'll need an access token for that one, see this: http://developers.wixrestaurants.com/Authorization
