### ISSUE TITLE
unable to generate access token

### ISSUE THREAD

**Issue by hoian2019** [wix/wix-restaurants-api#21]
When send POST to wix restaurant app for access_token, getting bad request.

![image](https://user-images.githubusercontent.com/58671838/70486734-03e21e80-1b47-11ea-894c-d89b17974d0c.png)

**Comment by hoian2019** [comment]
@guybenron, Hi Guy, I can't get access_token to access Wix Restaurant API. Can you please help?

**Comment by tj1122** [comment]
was this ever resolved?
