### ISSUE TITLE
Set of Curl examples

### ISSUE THREAD

**Issue by parshim** [wix/wix-restaurants-api#4]
Hi!

I am looking for curl examples for:

1) Making authorization call (acquire token)

2) Pull new orders 

Same operations as can be found in this java example:

 https://github.com/wix/wix-restaurants-java-sdk/blob/master/wix-restaurants-java-examples/src/main/java/com/wix/restaurants/examples/RetrieveNewOrdersExample.java

Thanks!

**Comment by dleshem** [comment]
1.
There are multiple ways to retrieve an access token, depending on your use-case.

A common use-case is if you have a Wix site. In this case, you can follow the curl example in http://developers.wixrestaurants.com/Authorization

Another common use-case is if you have a legacy OpenRest username/password (for example, for restaurants that work with food.co.il). In this case, you can use this curl:

```
curl -X "POST" -H "Content-Type: application/json" -d '{"type":"openrest.login","username":"user@example.com","password":"changeme"}' "https://auth.wixrestaurants.com/v1.0"
```

Either way, the response will be as described in the Authorization link above.

2.
The relevant request is "[query_orders](https://github.com/wix/openrest4j/blob/master/openrest4j-api/src/main/java/com/openrest/v1_1/QueryOrdersRequest.java)".

For example,
```
curl -X "POST" -H "Content-Type: application/json" -d '{"type":"query_orders","accessToken":"XXX","restaurantIds":["YYY"], "viewMode":"restaurant", "status":"new", "ordering":"asc", "limit":1000}' "https://api.wixrestaurants.com/v1.1"
```
where XXX is an access token with valid permissions, and YYY is the restaurant identifier.
