### ISSUE TITLE
API endpoint to add a product

### ISSUE THREAD

**Issue by yochail** [wix/wix-restaurants-api#7]
when editing the menu like ,:
[this](https://github.com/wix/wix-restaurants-api/issues/2
); #2 
and adding new items,
the menu in the website disappears.
maybe this is related to the fact i can't create the new items ids?

**Comment by dleshem** [comment]
@yochail, can you please add a code snippet? (just omit your access token)

Item IDs are simply [UUIDs](https://en.wikipedia.org/wiki/Universally_unique_identifier), you can just generate random ones for new items - most languages have standard libraries do do so.

**Comment by yochail** [comment]
@dleshem thx for the quick response.
My code is in C#, I use OpenrestClient, while creating the call to set_menu manually, as it didn't exist in the c# lib. 
After the first menu item i added (added "top1" and "top2" three times ), the menu in the website is gone, but i still getting it (with the change) when i call GetOrganizationInfo. when i try to remove the items i added, i get the following error: "{"timestamp":1514881087591,"error":"invalid_data","errorMessage":"menu is missing some existing items: Set(1254215935008876, 515365380520435, 4304621875059142, 3152680799276657, 7537951809683610, 7904406543622881)"}
also, when trying to remove items," (those are the ids [i don't know how he comes up with touse ids] of the added items).

the code:
`
 const string WIX_SINGLE_ENDPOINT_URI = "https://api.openrest.com/v1.1";
        static void Main(string[] args)
        {

            var restID = "5380353506276482";
            var rest = GetOrganizationInfo(restID);
            //Console.WriteLine(rest.ToString());
            var fullInfo = JsonConvert.DeserializeObject<Response<RestaurantFullInfo>>(rest);
            var menu = fullInfo.value.menu;



            List<string> toppingsList = new List<string>();
            toppingsList.Add("top1");
            toppingsList.Add("top2");
            List<string> toppingsIDList = new List<string>();

            foreach(var topping in toppingsList)
            {
                var newItem = new Item();
                var title = new Dictionary<string, string>();
                title.Add("en_US", topping);
                newItem.restaurantId = restID;
                newItem.title = title;
                newItem.id = topping + "_" + topping.GetHashCode();
                menu.items.Add(newItem);
                toppingsIDList.Add(newItem.id);
                //var list = menu.items.ToList();
                //var t = list.RemoveAll(x => x.title.First().Value == "top1" || x.title.First().Value == "top2");
                //menu.items = list;
            }
            

            foreach (var item in menu.items)
            {
                //for pizzas only
                if (item.variations.Any())
                {
                    var variation = new Variation();
                    var title = new Dictionary<string, string>();
                    title.Add("en_US", "accept my nigge");
                    variation.displayType = "choice";
                    variation.title = title;
                    var prices = new Dictionary<string, int>();
                    variation.prices = prices;
                    variation.minNumAllowed = 0;
                    variation.maxNumAllowed = int.MaxValue;
                   

                    foreach (var top in toppingsIDList)
                    {
                        var price = new KeyValuePair<string, int>(top,1);
                        variation.prices.Add(price);
                    }
                    item.variations.Add(variation);
                    //var list = item.variations.ToList();
                    //list.RemoveAll(x => x.title.First().Value == "accept my nigge" || x.title.First().Value == "testtest");
                    item.variations = list;
                }
            }
            

            try
            {
                var menuStr = JsonConvert.SerializeObject(menu);
                Console.WriteLine(SetOrganizationInfo(restID, menuStr));
            }catch(Exception ex)
            {
                Console.WriteLine(ex);
            }

            Console.ReadLine();
        }



  public static string SetOrganizationInfo(string merchantID,string data)
        {

 
            try
            {
                using (var client = new HttpClient())
                {
                    var unformattedUrl = WIX_SINGLE_ENDPOINT_URI;

                    var postBodyJson = "{" +
                                         "\"accessToken\": \"***************************************\"," +
                                          "\"type\": \"set_menu\"," +
                                          "\"organizationId\": " + merchantID + ","+
                                            "\"menu\": " + data +
                                          "}";

                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    System.Net.ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };


                    var response =
                        client.PostAsync(unformattedUrl, new StringContent(postBodyJson, Encoding.UTF8, "application/json"))
                            .Result;

                    if (response.IsSuccessStatusCode)
                    {
                        // by calling .Result you are performing a synchronous call
                        var responseContent = response.Content;

                        // by calling .Result you are synchronously reading the result
                        var responseString = responseContent.ReadAsStringAsync().Result;

                        return responseString;
                    }
                }
            }
            catch (HttpRequestException hre)

            {
                Console.WriteLine("Error:" + hre.Message);
            }
            catch (TaskCanceledException)
            {
                Console.WriteLine("Request canceled.");
            }
            return string.Empty;
        }

`

 public static string GetOrganizationInfo(string merchantID)
        {
            try
            {
                using (var client = new HttpClient())
                {
                    var unformattedUrl = WIX_SINGLE_ENDPOINT_URI;

                    var postBodyJson = "{" +
                                          "\"type\": \"get_organization_full\"," +
                                          "\"organizationId\": " + merchantID +
                                          "}";

                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    System.Net.ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };


                    var response =
                        client.PostAsync(unformattedUrl, new StringContent(postBodyJson, Encoding.UTF8, "application/json"))
                            .Result;

                    if (response.IsSuccessStatusCode)
                    {
                        // by calling .Result you are performing a synchronous call
                        var responseContent = response.Content;

                        // by calling .Result you are synchronously reading the result
                        var responseString = responseContent.ReadAsStringAsync().Result;
                    
                        return responseString;
                    }
                }
            }
            catch (HttpRequestException hre)
            {
                Console.WriteLine("Error:" + hre.Message);
            }
            catch (TaskCanceledException)
            {
                Console.WriteLine("Request canceled.");
            }
            return string.Empty;
        }

**Comment by dleshem** [comment]
So, a few things-

1. The C# library is based on legacy OpenRest code and is not actively maintained. Some of its data model objects are incomplete, which may result in unexpected behavior when writing to the API (reading should be OK, worst case some fields will be missing). Specifically in your case, I see the `Menu` object is missing the `sections` field which explains why your menu is deleted from the site.

2. The API URL is now `https://api.wixrestaurants.com/v1.1`

3. As the error message suggests, items cannot be deleted from a menu. You can remove them from menu sections, but they must remain in `Menu.items`.

I suggest you either develop your own C# client based on the [Wix Restaurants API documentation](http://developers.wixrestaurants.com), or switch to a supported SDK ([Java ](https://github.com/wix/wix-restaurants-java-sdk)/ [JavaScript](https://github.com/wix/wix-restaurants-js-sdk)).

**Comment by yochail** [comment]
seems that the JS version doesn't have the set_menu request. really was trying to avoid java but I'll try it anyway. thanks Dani.

**Comment by dleshem** [comment]
You can add this as an issue to https://github.com/wix/wix-restaurants-js-sdk
