### ISSUE TITLE
Restaurant Chain

### ISSUE THREAD

**Issue by MYiazou** [wix/wix-restaurants-api#8]
Hi,

I'd like to know about Restaurant Chains.
Our customer needs to open another Restaurant in another city. 
Does Wix Restaurant supports Restaurant's chain in one site?
If not. What is the solution for Restaurant's Chain?

Thanks in advance

**Comment by dleshem** [comment]
Hi @MYiazou - questions regarding Wix Restaurants products (rather than the Wix Restaurants API) are best directed to [Wix Support](https://support.wix.com/en/).
