### ISSUE TITLE
WebHook Content

### ISSUE THREAD

**Issue by MYiazou** [wix/wix-restaurants-api#9]
Hi,
I read Wix Restaurant Api for Sending WebHooks  and i noticed that every time an order submits to system WebHook receives Menu Object and Order Object.
What's the need for Menu Object? If we want to submit orders to our POS System?

Thanks In advance

**Comment by dleshem** [comment]
The `Order` object lists the IDs of ordered items, and the `Menu` object has the full information for each item (title, description, etc).

You can ignore the menu data if you don't need it :)

**Comment by MYiazou** [comment]
thanks a lot
